version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password123}
      MYSQL_DATABASE: ${DB_NAME:-ecommerce_mahasiswa}
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-password123}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_PASSWORD:-password123}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: always
    depends_on:
      - mysql
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-8080}
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-password123}
      DB_NAME: ${DB_NAME:-ecommerce_mahasiswa}
      DB_PORT: 3306
      JWT_SECRET: ${JWT_SECRET:-secret_key_for_jwt_please_change_in_production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      APPWRITE_ENDPOINT: ${APPWRITE_ENDPOINT:-http://example.com/v1}
      APPWRITE_PROJECT_ID: ${APPWRITE_PROJECT_ID:-defaultprojectid}
      APPWRITE_API_KEY: ${APPWRITE_API_KEY:-defaultapikey}
      APPWRITE_BUCKET_ID: ${APPWRITE_BUCKET_ID:-defaultbucketid}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - seed-data:/app/src/.seed_data
    networks:
      - app-network
    command: npm start

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  seed-data:
    driver: local
